# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="TLZSEVS-ZA14024"

[TLZSEVS-ZA14024]
account = "TLZSEVS-ZA14024"
user = "ROHITH"
password = "Rohith@8885405754"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
