# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME=""

[]
account = ""
user = ""
password = ""
role = ""
warehouse = ""
database = ""
schema = ""
